/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicProductsIndexRouteImport } from './routes/_public/products/index'
import { Route as PublicHomeIndexRouteImport } from './routes/_public/_home/index'
import { Route as PublicProductsSlugRouteImport } from './routes/_public/products/$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHomeIndexRoute = PublicHomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsSlugRoute = PublicProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicHomeIndexRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/products/': typeof PublicProductsIndexRoute
}
export interface FileRoutesByTo {
  '/products/$slug': typeof PublicProductsSlugRoute
  '/': typeof PublicHomeIndexRoute
  '/products': typeof PublicProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/products/$slug': typeof PublicProductsSlugRoute
  '/_public/_home/': typeof PublicHomeIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products/$slug' | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to: '/products/$slug' | '/' | '/products'
  id:
    | '__root__'
    | '/_public'
    | '/_public/products/$slug'
    | '/_public/_home/'
    | '/_public/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_home/': {
      id: '/_public/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicHomeIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products/$slug': {
      id: '/_public/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof PublicProductsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicProductsSlugRoute: typeof PublicProductsSlugRoute
  PublicHomeIndexRoute: typeof PublicHomeIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicProductsSlugRoute: PublicProductsSlugRoute,
  PublicHomeIndexRoute: PublicHomeIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
